name: 'Update resource at LFM'
description: 'Publish resource update on LFM'
icon: 'activity'
color: 'purple'
inputs:
  resource-id:
    description: 'Which resource should be updated'
    required: true
  api-token:
    description: 'Access token'
    required: true
  file-path:
    description: 'Local path to the file you want to append'
    required: false
  version:
    description: 'Update version'
    required: false
  title:
    description: 'Update post title (optional if description specified)'
    required: false
  subtitle:
    description: 'Update post subtitle'
    required: false
  description:
    description: 'Update post description (optional if title specified, MD supported)'
    required: false
outputs:
  message:
    description: 'Message from the server'
runs:
  using: 'node12'
  main: 'index.js'
